use std::marker::PhantomData;

use axum::{http::HeaderValue, response::IntoResponse};
use axum_htmx::{HxEvent, HxResponseTrigger, SwapOption};
use maud::{Markup, Render, html};
use serde_json::{Value, json};

use crate::Id;

/// An htmx response containing an optional swap for the request target,
/// targeted `<hx-partial>` swaps, and client-side events.
///
/// Most code uses [`partial!`](crate::partial!); `HxPartial` is the builder
/// behind it.
///
/// ```
/// use vixen::{HxPartial, hx::SwapOption, id, maud::html};
///
/// #[id]
/// struct NotesId;
///
/// let response = HxPartial::new()
///     .main(html! { "swapped into the request target" }) // optional
///     .target(NotesId, html! { li { "a note" } })
///     .target_swap("#toaster", SwapOption::BeforeEnd, html! { "saved" });
///
/// assert_eq!(
///     response.render().into_string(),
///     concat!(
///         "swapped into the request target",
///         r##"<hx-partial hx-target="#notes"><li>a note</li></hx-partial>"##,
///         r##"<hx-partial hx-target="#toaster" hx-swap="beforeend">saved</hx-partial>"##,
///     )
/// );
/// ```
///
/// # Type state
///
/// `S` tracks whether the response contains markup; events do not count. `M`
/// tracks whether the main body is set. The marker types are exported from
/// [`markers`](crate::markers). Only `HxPartial<Filled, M>` implements
/// `IntoResponse`, and [`main`](HxPartial::main) is available only while `M` is
/// [`NoMain`]. Empty responses and a second main body therefore fail to compile.
///
/// Use [`HxPartialResponse`] when a handler needs a concrete return type for a
/// response with targeted parts only.
pub struct HxPartial<S = Empty, M = NoMain> {
    state: State,
    _state: PhantomData<fn() -> (S, M)>,
}

/// A concrete handler return type for one or more targeted parts with no main
/// body. The response can also trigger events.
///
/// A [`Part`] converts directly into this type, so a branch can end in
/// `.into()`:
///
/// ```
/// use vixen::{HxPartialResponse, Part, maud::html};
///
/// fn saved() -> HxPartialResponse {
///     Part::new("#status", html! { "saved" }).into()
/// }
/// ```
///
/// The concrete type for a response with a main body is
/// `HxPartial<Filled, HasMain>`; it is usually returned as `impl IntoResponse`.
pub type HxPartialResponse = HxPartial<Filled>;

/// Type state before any content has been added.
pub struct Empty;
/// Type state after at least one piece of content has been added.
pub struct Filled;

/// Type state before the main body has been set.
pub struct NoMain;
/// Type state after the main body has been set.
pub struct HasMain;

struct State {
    main: Option<Markup>,
    parts: Vec<Part>,
    events: Vec<HxEvent>,
}

/// Content for an htmx target, with an optional swap strategy.
pub struct Part {
    target: Selector,
    swap: Option<SwapOption>,
    content: Markup,
}

impl Part {
    /// Creates a part for `target`.
    pub fn new(target: impl Into<Selector>, content: Markup) -> Self {
        Part {
            target: target.into(),
            swap: None,
            content,
        }
    }

    /// Sets the swap strategy.
    pub fn swap(mut self, swap: SwapOption) -> Self {
        self.swap = Some(swap);
        self
    }

    /// Returns the content without its `<hx-partial>` wrapper, for rendering
    /// the same content as part of a full page.
    pub fn render(self) -> Markup {
        self.content
    }
}

impl Render for Part {
    fn render_to(&self, buffer: &mut String) {
        buffer.push_str(&self.content.0);
    }
}

impl IntoResponse for Part {
    fn into_response(self) -> axum::response::Response {
        HxPartial::from(self).into_response()
    }
}

/// A collection of [`Part`]s.
pub struct Parts {
    /// Parts in response order.
    pub parts: Vec<Part>,
}

impl From<Part> for Parts {
    fn from(part: Part) -> Self {
        Self { parts: vec![part] }
    }
}

impl From<Part> for HxPartial<Filled> {
    fn from(part: Part) -> Self {
        HxPartial::new().part(part)
    }
}

impl From<Vec<Part>> for Parts {
    fn from(parts: Vec<Part>) -> Self {
        Self { parts }
    }
}

/// A CSS selector used by `hx-target` and `hx-sync`.
///
/// APIs that target an element accept `impl Into<Selector>`. Strings are kept
/// as written (`"#list"`, `"closest form"`). Types declared with
/// [`#[id]`](macro@crate::id), including ids generated by
/// [`#[fragment]`](macro@crate::fragment), convert to their `#id` selector.
#[derive(Clone)]
pub struct Selector(pub String);

impl From<Selector> for String {
    fn from(value: Selector) -> Self {
        value.0
    }
}

impl<T: Id> From<T> for Selector {
    fn from(id: T) -> Self {
        id.sel()
    }
}

impl From<&str> for Selector {
    fn from(value: &str) -> Self {
        Self(value.to_string())
    }
}

impl From<String> for Selector {
    fn from(value: String) -> Self {
        Self(value)
    }
}

impl Render for Selector {
    fn render_to(&self, buffer: &mut String) {
        self.0.render_to(buffer);
    }
}

impl<S, M> HxPartial<S, M> {
    fn cast<S2, M2>(self) -> HxPartial<S2, M2> {
        HxPartial {
            state: self.state,
            _state: PhantomData,
        }
    }
}

impl HxPartial<Empty, NoMain> {
    /// Creates an empty builder. Add a main body or part before returning it.
    pub fn new() -> Self {
        HxPartial {
            state: State {
                main: None,
                parts: Vec::new(),
                events: Vec::new(),
            },
            _state: PhantomData,
        }
    }
}

impl Default for HxPartial<Empty, NoMain> {
    fn default() -> Self {
        Self::new()
    }
}

impl<S> HxPartial<S, NoMain> {
    /// Sets the markup for the request's original target. It is rendered
    /// outside the `<hx-partial>` blocks.
    ///
    /// Omit the main body to leave the requesting element untouched. This
    /// method can only be called once.
    pub fn main(mut self, content: impl Into<Markup>) -> HxPartial<Filled, HasMain> {
        self.state.main = Some(content.into());
        self.cast()
    }
}

impl<S, M> HxPartial<S, M> {
    /// One `<hx-partial>` block, aimed at `target`.
    ///
    /// ```html
    /// <hx-partial hx-target="#notes">...</hx-partial>
    /// ```
    pub fn target(self, target: impl Into<Selector>, content: Markup) -> HxPartial<Filled, M> {
        self.part(Part::new(target, content))
    }

    /// One `<hx-partial>` block, aimed at `target` with the swap spelled out.
    ///
    /// ```html
    /// <hx-partial hx-target="#toast" hx-swap="beforeend">...</hx-partial>
    /// ```
    pub fn target_swap(
        self,
        target: impl Into<Selector>,
        swap: SwapOption,
        content: Markup,
    ) -> HxPartial<Filled, M> {
        self.part(Part::new(target, content).swap(swap))
    }

    /// Adds a preconfigured [`Part`].
    pub fn part(mut self, part: impl Into<Part>) -> HxPartial<Filled, M> {
        self.state.parts.push(part.into());
        self.cast()
    }

    /// Adds a group of response parts.
    pub fn parts(mut self, parts: impl Into<Parts>) -> HxPartial<Filled, M> {
        self.state.parts.extend(parts.into().parts);
        self.cast()
    }

    /// Adds a part, event, or other bare [`partial!`](crate::partial!) entry.
    pub fn entry<E: PartialEntry>(self, entry: E) -> HxPartial<E::State<S>, M> {
        entry.add_to(self)
    }

    /// Adds an event to the response's `HX-Trigger` header.
    ///
    /// Missing or `null` event data is encoded as `{}` rather than the `null`
    /// value that htmx 4 rejects.
    ///
    /// ```
    /// use axum::response::IntoResponse;
    /// use vixen::{HxPartial, maud::html};
    ///
    /// let response = HxPartial::new()
    ///     .target("#status", html! { "saved" })
    ///     .event("todos:refresh")
    ///     .into_response();
    ///
    /// assert_eq!(response.headers()["hx-trigger"], r#"{"todos:refresh":{}}"#);
    /// ```
    pub fn event(mut self, event: impl Into<HxEvent>) -> Self {
        let mut event = event.into();
        if event.data.as_ref().is_none_or(Value::is_null) {
            event.data = Some(json!({}));
        }
        self.state.events.push(event);
        self
    }
}

impl<M> HxPartial<Filled, M> {
    /// Renders the main body first, followed by one `<hx-partial>` block per
    /// part in insertion order. Converting the value into a response adds the
    /// events to `HX-Trigger`.
    pub fn render(self) -> Markup {
        html! {
            @if let Some(main) = self.state.main {
                (main)
            }
            @for Part { target, swap, content } in self.state.parts {
                hx-partial hx-target=(target) hx-swap=[swap.map(swap_attr)] {
                    (content)
                }
            }
        }
    }
}

impl<M> IntoResponse for HxPartial<Filled, M> {
    fn into_response(mut self) -> axum::response::Response {
        let events = std::mem::take(&mut self.state.events);
        (HxResponseTrigger::normal(events), self.render()).into_response()
    }
}

/// A type accepted by [`partial!`](crate::partial!) without `=>`.
pub trait PartialEntry {
    /// The content state after adding this entry. Use [`Filled`] when the entry
    /// always adds markup; events and optional parts preserve `S`.
    type State<S>;

    /// Adds this entry to a partial response.
    fn add_to<S, M>(self, partial: HxPartial<S, M>) -> HxPartial<Self::State<S>, M>;
}

impl PartialEntry for Part {
    type State<S> = Filled;

    fn add_to<S, M>(self, partial: HxPartial<S, M>) -> HxPartial<Filled, M> {
        partial.part(self)
    }
}

impl PartialEntry for Parts {
    type State<S> = Filled;

    fn add_to<S, M>(self, partial: HxPartial<S, M>) -> HxPartial<Filled, M> {
        partial.parts(self)
    }
}

impl PartialEntry for Vec<Part> {
    type State<S> = Filled;

    fn add_to<S, M>(self, partial: HxPartial<S, M>) -> HxPartial<Filled, M> {
        partial.parts(self)
    }
}

impl PartialEntry for Option<Part> {
    type State<S> = S;

    fn add_to<S, M>(self, mut partial: HxPartial<S, M>) -> HxPartial<S, M> {
        partial.state.parts.extend(self);
        partial
    }
}

impl PartialEntry for HxEvent {
    type State<S> = S;

    fn add_to<S, M>(self, partial: HxPartial<S, M>) -> HxPartial<S, M> {
        partial.event(self)
    }
}

pub(crate) fn swap_attr(swap: SwapOption) -> String {
    HeaderValue::from(swap)
        .to_str()
        .unwrap_or_default()
        .to_owned()
}

/// Builds an [`HxPartial`] response.
///
/// Each entry can be:
///
/// - `_ => content` for the main response body;
/// - `target => content` for a targeted swap;
/// - `(target, swap) => content` for a targeted swap with an explicit strategy;
/// - a [`Fragment`](crate::Fragment) for an `outerHTML` swap targeting its
///   element;
/// - a [`Part`], an optional `Part`, or a collection such as [`Parts`] or
///   `Vec<Part>`;
/// - an [`HxEvent`](crate::hx::HxEvent) for the `HX-Trigger` header;
/// - any other type that implements [`PartialEntry`].
///
/// The main body, when present, must come first. At least one entry must add
/// markup; an event-only response does not compile.
///
/// ```
/// use vixen::{
///     Part, fragment,
///     hx::{HxEvent, SwapOption},
///     id,
///     maud::{Markup, html},
///     partial,
/// };
///
/// #[fragment]
/// fn review_list() -> Markup {
///     html! { ul id=(Self) { li { "Sturdy." } } }
/// }
///
/// #[id]
/// struct ShelfCountId;
///
/// fn toast(text: &str) -> Part {
///     Part::new("#toaster", html! { (text) }).swap(SwapOption::BeforeEnd)
/// }
///
/// let response = partial!(
///     _ => html! { div.alert { "Thanks!" } },
///     review_list(),
///     ShelfCountId => html! { "12" },
///     ("#reviews", SwapOption::AfterBegin) => html! { li { "Sturdy." } },
///     toast("Saved"),
///     HxEvent::new("reviews:refresh"),
/// );
/// ```
#[macro_export]
macro_rules! partial {
    (@acc $p:expr;) => {
        $p
    };
    (@acc $p:expr; ($target:expr, $swap:expr) => $content:expr $(, $($rest:tt)*)?) => {
        $crate::partial!(@acc $p.target_swap($target, $swap, $content); $($($rest)*)?)
    };
    (@acc $p:expr; $target:expr => $content:expr $(, $($rest:tt)*)?) => {
        $crate::partial!(@acc $p.target($target, $content); $($($rest)*)?)
    };
    (@acc $p:expr; $entry:expr $(, $($rest:tt)*)?) => {
        $crate::partial!(@acc $p.entry($entry); $($($rest)*)?)
    };
    (_ => $main:expr $(, $($rest:tt)*)?) => {
        $crate::partial!(@acc $crate::HxPartial::new().main($main); $($($rest)*)?)
    };
    ($($entry:tt)+) => {
        $crate::partial!(@acc $crate::HxPartial::new(); $($entry)+)
    };
}

#[cfg(test)]
mod tests {
    use super::*;

    fn toast() -> Part {
        Part::new("#toaster", html! { "saved" }).swap(SwapOption::BeforeEnd)
    }

    fn rows() -> Markup {
        html! { tr { td { "row" } } }
    }

    fn both() -> Parts {
        vec![Part::new("#rows", rows()), toast()].into()
    }

    fn trigger(response: impl IntoResponse) -> Option<Value> {
        let response = response.into_response();
        let header = response.headers().get("hx-trigger")?;
        Some(serde_json::from_slice(header.as_bytes()).unwrap())
    }

    #[test]
    fn a_bare_part_and_a_targeted_entry_render_in_order() {
        let html = partial!(toast(), "#rows" => rows()).render().into_string();
        assert_eq!(
            html,
            concat!(
                r##"<hx-partial hx-target="#toaster" hx-swap="beforeend">saved</hx-partial>"##,
                r##"<hx-partial hx-target="#rows"><tr><td>row</td></tr></hx-partial>"##,
            )
        );
    }

    #[test]
    fn a_tuple_target_spells_out_the_swap() {
        let html = partial!(("#rows", SwapOption::AfterEnd) => rows())
            .render()
            .into_string();
        assert_eq!(
            html,
            r##"<hx-partial hx-target="#rows" hx-swap="afterend"><tr><td>row</td></tr></hx-partial>"##
        );
    }

    #[test]
    fn entries_evaluate_in_order() {
        let mut n = 0;
        let mut next = || {
            n += 1;
            Part::new(format!("#p{n}"), html! {})
        };
        let html = partial!(next(), next()).render().into_string();
        assert_eq!(
            html,
            concat!(
                r##"<hx-partial hx-target="#p1"></hx-partial>"##,
                r##"<hx-partial hx-target="#p2"></hx-partial>"##,
            )
        );
    }

    #[test]
    fn an_absent_part_renders_nothing() {
        let html = partial!(None::<Part>, "#rows" => rows(), Some(toast()))
            .render()
            .into_string();
        assert_eq!(
            html,
            concat!(
                r##"<hx-partial hx-target="#rows"><tr><td>row</td></tr></hx-partial>"##,
                r##"<hx-partial hx-target="#toaster" hx-swap="beforeend">saved</hx-partial>"##,
            )
        );
    }

    #[test]
    fn events_are_sent_with_data() {
        let close = HxEvent {
            name: "dialog:close".to_owned(),
            data: Some(json!({ "id": "m" })),
        };
        let nulled = HxEvent {
            name: "nulled".to_owned(),
            data: Some(Value::Null),
        };
        let response = partial!(close, toast(), HxEvent::new("rows:refresh"), nulled);
        assert_eq!(
            trigger(response),
            Some(json!({ "dialog:close": { "id": "m" }, "rows:refresh": {}, "nulled": {} }))
        );
    }

    #[test]
    fn a_response_without_events_has_no_trigger() {
        assert_eq!(trigger(partial!(toast())), None);
    }

    #[test]
    fn parts_spread_in_place() {
        let html = partial!(toast(), both()).render().into_string();
        assert_eq!(
            html,
            concat!(
                r##"<hx-partial hx-target="#toaster" hx-swap="beforeend">saved</hx-partial>"##,
                r##"<hx-partial hx-target="#rows"><tr><td>row</td></tr></hx-partial>"##,
                r##"<hx-partial hx-target="#toaster" hx-swap="beforeend">saved</hx-partial>"##,
            )
        );
    }
}
