[workspace]
resolver = "3"
members = ["vixen", "vixen-bundler", "vixen-macros", "examples/counter", "examples/todos"]

[workspace.package]
edition = "2024"
version = "0.1.0"
rust-version = "1.97"
license = "MIT"
repository = "https://github.com/borolgs/vixen"
publish = false

[workspace.lints.rust]

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"
private_intra_doc_links = "deny"
bare_urls = "warn"

[workspace.dependencies]
axum = { version = "0.8.8", features = ["macros"] }
axum-extra = { version = "0.12.5", features = ["form", "typed-routing"] }
# htmx 4
# https://github.com/robertwayne/axum-htmx/pull/38
axum-htmx = { git = "https://github.com/borolgs/axum-htmx", branch = "v4", features = [
  "v4",
  "serde",
  "auto-vary",
] }
maud = { version = "0.27.0", features = ["axum"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.49.0", features = ["full"] }
