[package]
name = "axum-vixen"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "An axum-based library for rapid web development, currently focused on the view layer: axum + maud + htmx."
keywords = ["axum", "htmx", "maud", "web", "ssr"]
categories = ["web-programming", "web-programming::http-server"]

[lib]
name = "vixen"

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
basecoatui = []

[dependencies]
axum-vixen-macros = { path = "../vixen-macros", version = "0.1.2" }
axum-vixen-bundler = { path = "../vixen-bundler", version = "0.1.2" }

axum = { workspace = true }
axum-htmx = { workspace = true }
axum-extra = { workspace = true }
maud = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
trybuild = "1.0.121"
