[package]
name = "shop"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
tokio = { workspace = true }
maud = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
serde = { workspace = true }
anyhow = "1.0.104"
rusqlite = { version = "0.40.2", features = ["bundled"] }
strum = { version = "0.28.0", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"

axum-vixen = { path = "../../vixen", features = ["basecoatui"] }

[dev-dependencies]
axum-vixen = { path = "../../vixen", features = ["testing"] }

[build-dependencies]
axum-vixen = { path = "../../vixen" }
